### ISSUE TITLE
Explain  me

### ISSUE THREAD

**Issue by SophiToyber** [metadamu/task_learn#1]
Why did you use the String Builder instead of the usual string, what is the reason for choosing?

https://github.com/metadamu/tasklearn/blob/718c02a250871ae2f4660810645051384c4d305a/src/Main.java#L6

**Comment by metadamu** [comment]
> Почему вы использовали String Builder вместо обычной строки, в чем причина выбора?
> 
> https://github.com/metadamu/tasklearn/blob/718c02a250871ae2f4660810645051384c4d305a/src/Main.java#L6

Strings in Java are immutable. When you change a String object in Java, a completely new object is created each time. If you are doing things to strings a lot in your code, you should use StringBuilder or StringBuffer because they are much faster and consume less memory than String
