### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by SophiToyber** [metadamu/task_learn#2]
In any language, you must use a certain style of writing code, for Java, the usual type is camel case, in the future, strictly observe this style in the code.
https://github.com/metadamu/tasklearn/blob/718c02a250871ae2f4660810645051384c4d305a/src/Main.java#L10

**Comment by SophiToyber** [comment]
Also try to name variables in English, except in cases where there are too many variables and it takes you too long

**Comment by metadamu** [comment]
Okay, thanks for the advice, I'll fix it now)

**Comment by metadamu** [comment]
> Также старайтесь называть переменные на английском языке, за исключением случаев, когда переменных слишком много и это занимает у вас слишком много времени.

Okay, thanks for the advice, I'll fix it now)
